### ISSUE TITLE
Container sağ-sol reklam banner

### ISSUE THREAD

**Issue by wemrekurt** [wemrekurt/Ogretmen-Ajandasi#26]
Sitenin sağına soluna (.ads-left ve .ads-right classları eklendim) dikey bannerların koyulması gerekiyor.

**Comment by wemrekurt** [comment]
@sametocak ayarlanmış yerleri ancak bir sıkıntı var. Mobilde gizlenmesi gerekiyor. Kenarlarda ince cizgi olarak görünüyor.

**Comment by sametocak** [comment]
Tamamlandı
