### ISSUE TITLE
Çoklu cihaz uyumlu (responsive) ön yüz tasarımı (Mobil, tablet ve masaüstü)

### ISSUE THREAD

**Issue by wemrekurt** [wemrekurt/Ogretmen-Ajandasi#3]

**Comment by wemrekurt** [comment]
Bana Özel:
![banaozel](https://user-images.githubusercontent.com/10333281/44548735-9dee3f80-a727-11e8-8e97-bb670c3f6dd7.png)

**Comment by wemrekurt** [comment]
Kredi kartı ödeme onay [dosya](https://github.com/wemrekurt/Ogretmen-Ajandasi/blob/master/app/views/orders/iyzico_callback.slim)

![kk_odeme_onay](https://user-images.githubusercontent.com/10333281/44549607-48676200-a72a-11e8-97b7-a7d49475e4e7.png)

**Comment by wemrekurt** [comment]
![kayit](https://user-images.githubusercontent.com/10333281/44553496-591dd500-a736-11e8-935c-54ac14d61ee1.png)

**Comment by sametocak** [comment]
Tamamlandı
